name: Shared functionality for the Build & Deploy workflows

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      gov_paas_password:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo run_id and run_number
      run |
        echo 'Run id is ${{ github.run_id }} and run number is ${{ github.run_number }}'
      
    - name: Checkout code onto job runner
      uses: actions/checkout@v2
      
    - name: Install Node.JS (v14)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install .Net (5.0)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install the Cloud Foundry CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf7-cli

    - name: Restore Node.JS dependencies
      run: npm ci
      working-directory: ./SeaPublicWebsite
      
    - name: Build SCSS and JS code
      run: npm run build
      working-directory: ./SeaPublicWebsite
      
    - name: Restore .Net dependencies
      run: dotnet restore
      
    - name: Build .Net code
      run: dotnet build --no-restore --configuration Release --output ./ci-server-build/

    - name: Push the app to Gov.UK PaaS
      run: |
        cf login -a api.cloud.service.gov.uk -u team-beisesassupport@softwire.com -p '${{ secrets.gov_paas_password }}' -o 'beis-domestic-energy-advice-service'
        cf target -s sea-alpha-${{ inputs.environment_name }}
        cf push sea-alpha-${{ inputs.environment_name }} --manifest manifest.yml
      working-directory: ./ci-server-build/
